"""Materialized context: a small always-on digest with progressive disclosure.

Poppy writes one generated file (``~/.poppy/context/poppy.md``):

- binding rules in full (few by design, and constraints must be exact),
- headlines for memories and scoped rules: title + trigger + short ref,
  with an explicit instruction to fetch the full entry on demand.

The digest is wired into a harness's native instruction mechanism by the
installer (a native include where supported, a managed block otherwise).
Nothing runs at session time, so nothing can break a session; and agents see
what exists without loading everything.
"""

from __future__ import annotations

from pathlib import Path

from . import library
from .agent import run_agent
from .util import PoppyError, atomic_write_text, load_json, now_iso, save_json, sha

BEGIN = "<!-- poppy:begin -->"
END = "<!-- poppy:end -->"

MAX_HEADLINES = 40
MAX_BINDING_RULES = 20
MAX_CHARS = 8000


def context_dir(home: Path) -> Path:
    return home / "context"


def digest_path(home: Path) -> Path:
    return context_dir(home) / "poppy.md"


def state_path(home: Path) -> Path:
    return context_dir(home) / "state.json"


def wiring_path(home: Path) -> Path:
    return context_dir(home) / "wiring.json"


def short_ref(entry: library.Entry) -> str:
    return entry.id.split("-")[-1][:6]


def _first_paragraph(body: str) -> str:
    return (body or "").strip().split("\n\n")[0].replace("\n", " ")


def _trigger(entry: library.Entry) -> str:
    trigger = str(entry.meta.get("trigger") or "").strip()
    if trigger:
        return trigger
    for line in (entry.body or "").splitlines():
        stripped = line.strip()
        if stripped.startswith(("Applies when:", "Use when:")):
            return stripped
    return ""


def _applicable(entry: library.Entry, host: str) -> bool:
    if entry.archived or entry.status != "active":
        return False
    if entry.scope == "machine":
        return str(entry.meta.get("machine") or "") == host
    return True


def _render(binding: list, memories: list, scoped_rules: list, dropped: int) -> str:
    lines = [
        BEGIN,
        "# Poppy memory index",
        "",
        "Generated by Poppy — do not edit. Full entries: `poppy library show <ref>` "
        "(short refs work). Fetch an entry before acting on anything it covers.",
        "",
        "## Rules (binding)",
        "",
    ]
    if binding:
        for entry in binding:
            lines.append(f"- [{entry.scope}] {entry.title}: {_first_paragraph(entry.body)}")
    else:
        lines.append("(none yet)")
    lines += ["", "## Memory index", ""]
    if memories:
        for entry in memories:
            trigger = _trigger(entry)
            suffix = f" — {trigger}" if trigger else ""
            lines.append(f"- [{entry.scope}] {entry.title} ({short_ref(entry)}){suffix}")
    else:
        lines.append("(none yet)")
    if scoped_rules:
        lines += ["", "## Scoped rules (apply in their scope; fetch before working there)", ""]
        for entry in scoped_rules:
            where = entry.meta.get("project") or entry.scope
            lines.append(f"- [{entry.scope}] {entry.title} ({short_ref(entry)}) — {where}")
    if dropped:
        lines += ["", f"(+{dropped} more — `poppy library list`)"]
    lines += ["", END]
    return "\n".join(lines) + "\n"


def build_digest(home: Path, cfg: dict) -> tuple[str, dict]:
    host = library.host_name()
    usage = library.load_usage(home)
    entries = [e for e in library.list_entries(home) if _applicable(e, host)]

    binding = [e for e in entries if e.kind == "rule" and e.scope in ("user", "machine")]
    scoped_rules = [e for e in entries if e.kind == "rule" and e.scope in ("project", "task")]
    memories = [e for e in entries if e.kind == "memory"]

    binding.sort(key=lambda e: (library.SCOPE_RANK.get(e.scope, 9), e.title.lower()))
    memories.sort(
        key=lambda e: (
            -int(usage.get(e.id, {}).get("uses", 0)),
            usage.get(e.id, {}).get("last_used") or "",
            e.title.lower(),
        )
    )
    scoped_rules.sort(key=lambda e: e.title.lower())

    dropped = 0
    if len(binding) > MAX_BINDING_RULES:
        dropped += len(binding) - MAX_BINDING_RULES
        binding = binding[:MAX_BINDING_RULES]
    if len(memories) > MAX_HEADLINES:
        dropped += len(memories) - MAX_HEADLINES
        memories = memories[:MAX_HEADLINES]

    text = _render(binding, memories, scoped_rules, dropped)
    while len(text) > MAX_CHARS and memories:
        memories = memories[:-1]
        dropped += 1
        text = _render(binding, memories, scoped_rules, dropped)

    stats = {
        "binding_rules": len(binding),
        "memories": len(memories),
        "scoped_rules": len(scoped_rules),
        "dropped": dropped,
        "chars": len(text),
    }
    return text, stats


def fingerprint(home: Path, cfg: dict) -> str:
    host = library.host_name()
    rows = sorted(
        (
            entry.id,
            entry.status,
            entry.title,
            entry.scope,
            str(entry.meta.get("last_verified") or ""),
            str(entry.meta.get("pinned") or ""),
            _trigger(entry),
        )
        for entry in library.list_entries(home)
    )
    return sha(repr(rows) + host, 16)


def export(home: Path, cfg: dict) -> dict:
    text, stats = build_digest(home, cfg)
    context_dir(home).mkdir(parents=True, exist_ok=True)
    atomic_write_text(digest_path(home), text)
    save_json(
        state_path(home),
        {"generated_at": now_iso(), "fingerprint": fingerprint(home, cfg), "stats": stats},
    )
    return {"path": str(digest_path(home)), **stats}


def status(home: Path, cfg: dict) -> dict:
    state = load_json(state_path(home), {}) or {}
    wiring = load_json(wiring_path(home), {"targets": []}) or {"targets": []}
    targets = []
    for target in wiring.get("targets", []):
        path = Path(str(target.get("file", ""))).expanduser()
        content = path.read_text(encoding="utf-8", errors="replace") if path.is_file() else ""
        targets.append({"file": str(path), "exists": path.is_file(), "block": BEGIN in content})
    return {
        "digest": str(digest_path(home)),
        "exists": digest_path(home).is_file(),
        "generated_at": state.get("generated_at"),
        "fresh": bool(state.get("fingerprint")) and state.get("fingerprint") == fingerprint(home, cfg),
        "stats": state.get("stats") or {},
        "targets": targets,
    }


def wire(home: Path, cfg: dict, target: Path) -> dict:
    """Insert (or refresh) the digest as a managed block inside *target*."""
    export(home, cfg)
    block = digest_path(home).read_text(encoding="utf-8").strip()
    target = Path(target).expanduser()
    target.parent.mkdir(parents=True, exist_ok=True)
    existing = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else ""
    if BEGIN in existing and END in existing:
        start = existing.index(BEGIN)
        end = existing.index(END) + len(END)
        updated = existing[:start] + block + existing[end:]
    elif existing.strip():
        updated = existing.rstrip() + "\n\n" + block + "\n"
    else:
        updated = block + "\n"
    mode = target.stat().st_mode & 0o777 if target.is_file() else 0o644
    atomic_write_text(target, updated, mode=mode)
    wiring = load_json(wiring_path(home), {"targets": []}) or {"targets": []}
    entries = [t for t in wiring.get("targets", []) if t.get("file") != str(target)]
    entries.append({"file": str(target), "wired_at": now_iso()})
    save_json(wiring_path(home), {"targets": entries})
    return {"file": str(target), "mode": "block"}


def unwire(home: Path, cfg: dict, target: Path) -> dict:
    target = Path(target).expanduser()
    if not target.is_file():
        raise PoppyError(f"not a file: {target}")
    existing = target.read_text(encoding="utf-8", errors="replace")
    if BEGIN in existing and END in existing:
        start = existing.index(BEGIN)
        end = existing.index(END) + len(END)
        updated = (existing[:start].rstrip() + "\n" + existing[end:].lstrip()).lstrip("\n")
        atomic_write_text(target, updated, mode=target.stat().st_mode & 0o777)
    wiring = load_json(wiring_path(home), {"targets": []}) or {"targets": []}
    entries = [t for t in wiring.get("targets", []) if t.get("file") != str(target)]
    save_json(wiring_path(home), {"targets": entries})
    return {"file": str(target), "removed": True}


def verify(home: Path, cfg: dict) -> tuple[bool, str]:
    """Prove the digest reaches a headless session (canary test)."""
    text, _stats = build_digest(home, cfg)
    needle = ""
    for line in text.splitlines():
        if line.startswith("- ["):
            needle = line.split("]", 1)[-1].strip()[:32]
            break
    if not needle:
        needle = "Poppy memory index"
    prompt = (
        "Context check. If your context contains a generated block from the tool Poppy "
        "(a memory index with rules and entry headlines), reply with its first entry line "
        "(the first line starting with '- [') or, if it has no entries, its title line. "
        "If you do not see such a block, reply exactly NONE."
    )
    try:
        result = run_agent("miner", prompt, cfg, home)
    except PoppyError as exc:
        return False, str(exc)
    output = (result.stdout or "") + "\n" + (result.stderr or "")
    if needle.lower() in output.lower():
        return True, f"digest visible in a headless session (matched {needle!r})"
    if "NONE" in output.upper():
        return False, "agent reported no Poppy block in its context — wiring is missing or broken"
    return False, f"could not confirm the digest in the agent's reply: {output[:200]!r}"
